service: dramatispersonae

package:
    artifact: .build/lambda/DramatisPersonae/lambda.zip

provider:
    name: aws
    httpApi:
        payload: '2.0'
    runtime: provided
    logs:
        httpApi: true
    iamRoleStatements:
        - Effect: Allow
          Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          Resource: "*"        

functions:
    httpGet:
        handler: DramatisPersonae
        memorySize: 128
        events:
        - httpApi:
            method: GET
            path: /api
