service: dramatispersonae

package:
    artifact: .build/lambda/DramatisPersonae/lambda.zip

provider:
    name: aws
    region: us-west-2
    runtime: provided
    iamRoleStatements:
        - Effect: Allow
          Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          Resource: "*"        

functions:
  Endpoint:
    name: ${self:service.name}-endpoint-${self:provider.stage}
    handler: DramatisPersonae
    memorySize: 1024
    environment:
      DEPLOYMENT_STAGE: ${env:DEPLOYMENT_STAGE}
    events:
      - http:
          path: /invoke
          method: post
      - http:
          path: /invoke
          method: get
